# Generated by Django 3.2.18 on 2023-05-20 11:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0005_auto_20230515_1055'),
    ]

    operations = [
        migrations.CreateModel(
            name='CameraType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('dslr_camera', 'DSLR Camera'), ('mirrorless_camera', 'Mirrorless Camera'), ('bridge_camera', 'Bridge Camera'), ('compact_digital_camera', 'Compact Digital Camera'), ('smartphone', 'Smartphone')], max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='PhotoType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('abstract', 'Abstract'), ('action', 'Action'), ('animals', 'Animals'), ('architecture', 'Architecture'), ('black_and_white', 'Black and White'), ('colors', 'Colors'), ('city', 'City'), ('fashion', 'Fashion'), ('food', 'Food'), ('landscape', 'Landscape'), ('macro', 'Macro'), ('manipulation', 'Manipulation'), ('nature', 'Nature'), ('night', 'Night'), ('objects', 'Objects'), ('people', 'People'), ('sports', 'Sports'), ('transportation', 'Transportation'), ('water', 'Water'), ('wedding', 'Wedding'), ('other', 'Other')], max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='post',
            name='camera_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='posts.cameratype'),
        ),
        migrations.AlterField(
            model_name='post',
            name='photo_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='posts.phototype'),
        ),
    ]
