# Generated by Django 3.2.18 on 2023-05-20 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0006_auto_20230520_1127'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='camera_type',
            field=models.CharField(choices=[('dslr_camera', 'DSLR Camera'), ('mirrorless_camera', 'Mirrorless Camera'), ('bridge_camera', 'Bridge Camera'), ('compact_digital_camera', 'Compact Digital Camera'), ('smartphone', 'Smartphone')], default='Other', max_length=100),
        ),
        migrations.AlterField(
            model_name='post',
            name='photo_type',
            field=models.CharField(choices=[('abstract', 'Abstract'), ('action', 'Action'), ('animals', 'Animals'), ('architecture', 'Architecture'), ('black_and_white', 'Black and White'), ('colors', 'Colors'), ('city', 'City'), ('fashion', 'Fashion'), ('food', 'Food'), ('landscape', 'Landscape'), ('macro', 'Macro'), ('manipulation', 'Manipulation'), ('nature', 'Nature'), ('night', 'Night'), ('objects', 'Objects'), ('people', 'People'), ('sport', 'Sport'), ('transportation', 'Transportation'), ('water', 'Water'), ('wedding', 'Wedding')], default='Other', max_length=100),
        ),
        migrations.DeleteModel(
            name='CameraType',
        ),
        migrations.DeleteModel(
            name='PhotoType',
        ),
    ]
