# Generated by Django 3.2.18 on 2023-05-20 12:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0007_auto_20230520_1211'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='camera_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='posts.cameratype'),
        ),
        migrations.AlterField(
            model_name='post',
            name='photo_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='posts.phototype'),
        ),
    ]
