# Generated by Django 3.2.18 on 2023-05-15 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_profile_camera_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(default='../default-profile_eu7hoo', upload_to='images/'),
        ),
    ]
