# Generated by Django 3.2.18 on 2023-05-15 11:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0003_alter_profile_camera_type'),
        ('profiles', '0003_alter_profile_image'),
    ]

    operations = [
    ]
